image: ruby:2.4

cache:
  paths:
    - vendor/

variables:
  JEKYLL_ENV: production

before_script:
  - gem install bundler --no-rdoc --no-ri
  - bundle install --path vendor

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
    - master
