---
title: Meritxell Bayarri
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/articles/:title"
- scope:
    path: assets/**
  values:
    sitemap: false
repository: rogervila/rogervila.github.io
cloudinary:
  base: https://res.cloudinary.com/meritxell/image/upload/
chatra:
  id: 45ad3NniE7rko5YLQ
commentbox_io:
  id: 5695770351108096-proj
google_analytics:
  id: UA-144172779-1
cookiebot:
  id: a17a87a6-d9af-4827-8917-0e3d8103a447
lang: es
description: Meritxell Bayarri
url: https://meritxellbayarri.github.io/
author: meribayarri
twitter:
  username: meribayarri
  card: summary
  hashtag: meribayarri
github:
  username: meribayarri
linkedin: https://es.linkedin.com/in/meritxell-bayarri
logo: https://res.cloudinary.com/meritxell/image/upload/f_auto,q_auto:best,w_112,h_28,c_lpad,b_white,dpr_auto/logo
social:
  name: Meritxell Bayarri
  links:
  - https://twitter.com/meribayarri
webmaster_verifications:
  google: svYS4Zm9S-Y3JNmrUV9ftjAQhKdTsuc8srqFXUdzFUc
  bing: 90A85818F3015458A2935CCC097A287C
paginate: 9
paginate_path: "/articles/page/:num/"
sass:
  sass_dir: _sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- Dockerfile
- docker-compose.yml
- ".editorconfig"
- ".gitignore"
- ".dockerignore"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-gist
- jekyll-github-metadata
