---
title: Meritxell Bayarri
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  tags:
    title: Tags
    output: true
  texts:
    title: Texts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
paginate: 6
paginate_path: "/:num/"
plugins:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate
exclude:
- package.json
- package-lock.json
- webpack.mix.js
- mix-manifest.json
- Gemfile
- Gemfile.lock
- node_modules
