---
title: Meritxell Bayarri - SEO Content Writer
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  portfolio:
    title: portfolio
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    sitemap: true
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title"
    sitemap: true
- scope:
    path: assets/**/*
  values:
    sitemap: false
person: Meritxell Bayarri
position: SEO Content writer
email: contact@meritxellbayarri.com
repository: meritxellbayarri/meritxellbayarri.github.io
cloudinary:
  base: https://res.cloudinary.com/meritxell/image/upload/
lang: en
description: Meritxell Bayarri
url: https://meritxellbayarri.github.io/
author: meribayarri
twitter:
  username: meribayarri
  card: summary
  hashtag: meribayarri
github:
  username: meribayarri
linkedin: https://es.linkedin.com/in/meritxell-bayarri
logo: https://res.cloudinary.com/meritxell/image/upload/f_auto,q_auto:best,w_128,h_128,c_lpad,b_white,dpr_auto/meritxellbayarri
webmaster_verifications:
  google: svYS4Zm9S-Y3JNmrUV9ftjAQhKdTsuc8srqFXUdzFUc
  bing: 90A85818F3015458A2935CCC097A287C
social:
  name: Meritxell Bayarri
  links:
  - https://twitter.com/meribayarri
  - https://es.linkedin.com/in/meritxell-bayarri
paginate: 9
paginate_path: "/blog/page/:num/"
sass:
  sass_dir: _sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- ".gitignore"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-gist
- jekyll-github-metadata
- jekyll-redirect-from
