---
title: Meritxell Bayarri
timezone: Europe/Madrid
cloudinary:
  url: 'https://res.cloudinary.com/puntpla/image/upload/f_auto,q_auto,dpr_auto,w_auto,c_scale,g_auto/'
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
paginate: 6
paginate_path: "/:num/"
plugins:
- plugins:
- github-pages
exclude:
- package.json
- package-lock.json
- webpack.mix.js
- mix-manifest.json
- Gemfile
- Gemfile.lock
- node_modules
